# Generated by Django 5.2.17 on 2026-10-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageasset",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
