# Generated by Django 5.2.17 on 2026-10-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_imageasset_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageasset",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
